### ISSUE TITLE
Seleção: Mecanismos para extração de dados textuais anotados

### ISSUE THREAD

**Issue by rafaelglater** [MPMG-DCC-UFMG/C04#11]
Mecanismos para processar dados retornados em formato HTML ou similar (XML, etc).

**Comment by caiocvsilva** [comment]
Esta tarefa será dividida em outras menores: 
- #101 Tabelas HTML para CSV
- Div para CSV
- Detector de estrutura de página (se o conteúdo está em tabela, div, <p> ...)
