### ISSUE TITLE
Civilidade: Mecanismos para camuflagem dos coletores

### ISSUE THREAD

**Issue by rafaelglater** [MPMG-DCC-UFMG/C04#20]
- [x] Rotacionar IPs (via proxies do Tor ou de terceiros)
- [x] Rotacionar User-Agents
- [x] Gerenciar taxa de requisições por tempo
- [x] Condicionar uso de proxies para determinadas regiões
- [ ] Incorporar aleatoriedade: Movimentos do mouse, tempo de permanência numa página, etc  
- [x] Gerenciar cookies (para webdrivers)
- [ ] Detectar Honeypots
- [ ] "Fingerprints" consistentes

**Comment by gabrielcrds** [comment]
Rotacionamento de IP, trocar variáveis do header do selenium...

**Comment by elvesrodrigues** [comment]
- [ ] Rotacionar IPs (via proxies do Tor ou de terceiros)
- [ ] Rotacionar User-Agents
- [ ] Gerenciar taxa de requisições por tempo
- [ ] Gerenciar cookies (para webdrivers)
- [ ] Condicionar uso de proxies para determinadas regiões
- [ ] Detectar Honeypots
- [ ] "Fingerprints" consistentes
- [ ] Incorporar aleatoriedade: Movimentos do mouse, tempo de permanência numa página, etc

**Comment by elvesrodrigues** [comment]
Por questão de simplicidade, essa issue trata exclusivamente de mecanismos de camuflagens para o Selenium. Para outra ferramentas, como Scrapy e Scrapy-Selenium, outras issues serão criadas.

Funcionalidades:
- Rotacionar IPs via Tor
- Rotacionar user-agents (Firefox apenas, por enquanto)
- Delays aleatórios ou fixos entre requisições
- Gerenciamento de Cookies

Limitações/correções a fazer:
- Rotação de IPs apenas por Tor
    - Uma vez que um webdriver é instanciado, não é possível redefinir seu proxy. Para o caso do Tor, isso não é um problema pois o comando de alteração de IPs não necessita alterar o proxy.
    - Para rotacionar uma lista de proxies, será necessário contornar isso.
- Rotação de user-agents para o Chrome
    - A maneira como rotação de user-agents no Firefox é feita não é possível no Chrome. 
 
A funcionalidade de mover mouse aleatoriamente em curvas de Bézier, embora implementada, foi removida por se mostrar pouco prática.
