### ISSUE TITLE
Tribunais regionais do trabalho

### ISSUE THREAD

**Issue by gabrielcrds** [MPMG-DCC-UFMG/C04#25]
https://portal.trt3.jus.br/internet

**Comment by luiznery** [comment]
Acredito ser possível recuperar todos ou grande parte dos processos gerando os números sequencialmente da forma que é exemplificada nesse site. Também, pode ser mais simples extrair os dados a partir dele.  
http://as1.trt3.jus.br/consulta/consulta.htm
Tive algumas dificuldades para quebrar o captcha de áudio, o reconhecedor de voz do google faz um bom trabalho mas o problema é baixar o áudio. Não tentei quebrar o captcha de imagem mas parece que vale a pena tentar.
