### ISSUE TITLE
Lidar com redirecionamentos para arquivos

### ISSUE THREAD

**Issue by gabrielcrds** [MPMG-DCC-UFMG/C04#266]
Em algumas coletas o link de arquivos ficam escondidos em links que não são nomes de arquivos, mas que fazem redirecionamentos para arquivos. É necessário modificar o [middleware de redicirecionamentos](https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#module-scrapy.downloadermiddlewares.redirect) para capturar essas mudanças e redirecionar os arquivos pro downloader de arquivos.

Antes dos downloaders serem adicionados ao branch-master, basta descobrir como modificar o tratamento para essas urls (chamando outra função por ex. ao invés do parse).

Seria interessante testar o novo middleware junto com Scrapy Cluster e Scrapy Puppeteer.

**Comment by caiocvsilva** [comment]
De acordo com o tipo de redirecionamento que acontece nas páginas, a melhor forma de controlar isso é verificando o header da URL. Para isso é utilizado o request.header, e de dentro dele é extraída a informação de Content-type. Caso seja uma página web será do tipo text/html, caso contrário é um arquivo. Desta forma é possível direcionar os arquivos para o file_downloader.

O content-type não é uma informação infalível, existem formas de apresentar um content-type, mas o arquivo na realidade ser de outro tipo. Entretanto, é difícil realizar a checagem para confirmar o tipo da página. Uma das formas é utilizar uma função do PHP, file_info, que compara os primeiros bytes com um banco já conhecido, para predizer o tipo do arquivo. Novamente, não é infalível, mas pode ser um passo extra, caso seja necessário.
