### ISSUE TITLE
Tribunais regionais federais - TRF 2 #1

### ISSUE THREAD

**Issue by gabrielcrds** [MPMG-DCC-UFMG/C04#27]
https://eproc.trf2.jus.br/eproc/externo_controlador.php?acao=processo_consulta_publica

**Comment by filipefbn** [comment]
https://github.com/mozilla/geckodriver/issues/1065 (referenciado em várias outras issues também)

Download de mime-types arbitrários deixa o gecko webdriver "hanging" até dar timeout. Trocar para chromium-based?

**Comment by gabrielcrds** [comment]
De toda forma, tem uma função pronta initChromeWebdriver nesse código [crawler.py](https://github.com/MPMG-DCC-UFMG/C04/blob/master/diario-oficial-de-mg/crawler.py), se quiser usar como referencia.
