### ISSUE TITLE
Coleta - Licitações de Pirapetinga

### ISSUE THREAD

**Issue by gabrielcrds** [MPMG-DCC-UFMG/C04#288]
https://pirapetinga.mg.gov.br/transparencia/index.php?t=39

**Comment by gabrielcrds** [comment]
Esperando feature de pegar links para arquivos que não terminam em uma extensão. (#301)

**Comment by elvesrodrigues** [comment]
Foi necessário alterar o código da interface para coletar, pelas seguintes razões:

- O servidor bloqueava requisições da biblioteca requests, usada tanto para detectar o tipo do conteúdo da URL, bem como para baixar pequenos arquivos (`filter_type_of_urls` e `file_downloader`)
- Foi necessário permitir redirecionamento nas requisições feitas em `filter_type_of_urls` em `static_page`  
- Foi necessário expandir o filtro de URLs em `extract_files` para permitir qualquer arquivo
- Foi necessário alterar `download_small_file` para registrar o `filetype` do arquivo baixado vindo da resposta do servidor pois as URLs de arquivos não possuíam extensão explicitamente na URL
