### ISSUE TITLE
Coleta - Licitações de Cristais

### ISSUE THREAD

**Issue by gabrielcrds** [MPMG-DCC-UFMG/C04#290]
https://www.cristais.mg.gov.br/portal/editais/1

**Comment by lucasaug** [comment]
Dados em /datalake/ufmg/290-cristais.zip

**Comment by lucasaug** [comment]
Obs: o arquivo em /datalake/ufmg/c04/290-cristais.zip foi criado durante uma tentativa de envio dessa coleta, mas parece ter sido corrompido durante a transmissão. Não consegui apagar esse arquivo, mas ele deve ser ignorado. Se alguém com permissão de root puder tentar apagar o arquivo, pode ser uma boa ideia.
