### ISSUE TITLE
Coleta - Licitações Passavinte

### ISSUE THREAD

**Issue by gabrielcrds** [MPMG-DCC-UFMG/C04#304]
https://www.passavinte.mg.gov.br/processos-licitatorios/

**Comment by elvesrodrigues** [comment]
Não é possível coletar os arquivos das licitações pois a url de download não é habitual nem suportado pela interface. É utilizado o atributo `data-downloadurl` nas tags `a`, ao invés de `href` para os arquivos de download.

**Comment by elvesrodrigues** [comment]
Com as últimas alterações na interface (em especial de configurações avançadas) e outras alterações que deram origem a issue #356, foi possível realizar a coleta. 

O arquivo comprimido com os dados coletados estão em `304-licitacoes-passa-vinte.tar.gz`.
