### ISSUE TITLE
Configuração para baixar arquivos

### ISSUE THREAD

**Issue by louisaturn** [MPMG-DCC-UFMG/C04#331]
No formulário para criação ou edição de um coletor, seção "Tipo de Coletor" a opção de baixar arquivos aceita que o campo de inserção do regex seja vazio da seguinte forma:

"Baixar arquivos de url que casem com o regex (deixe em branco para não filtrar)"

Porém, ao deixar vazio, minha coleta não obteve nenhum arquivo. Funciona normalmente ao inserir uma regex adequada.

**Comment by gabrielcrds** [comment]
Resolvido no PR #336
