### ISSUE TITLE
Consulta de registros de preço

### ISSUE THREAD

**Issue by rafaelglater** [MPMG-DCC-UFMG/C04#34]
https://www.registrodeprecos.mg.gov.br/aasi/do/filtrarRPs

**Comment by caiocvsilva** [comment]
Estrutura dos diretórios salvos:

No primeiro nível existe uma pasta com a data em que foi rodado o crawler. Dentro desta, no segundo nível, existe uma pasta por entrada, numeradas sequencialmente (1 até o número de entradas). Dentro de cada pasta numerada, nível três, se encontram os arquivos html daquela entrada.
