### ISSUE TITLE
Despesas estaduais com diárias

### ISSUE THREAD

**Issue by rafaelglater** [MPMG-DCC-UFMG/C04#41]
http://transparencia.mg.gov.br/estado-pessoal/diarias

**Comment by LorenaMendes** [comment]
Página apresenta erro de _timeout_ desde 23/02/2020, impedindo a coleta durante os últimos dias. Até o momento, foi feita a coleta de metade dos dados de 2020.

**Comment by LorenaMendes** [comment]
Dados salvos na Curinga em /mnt/lorena/diarias.zip
