### ISSUE TITLE
Seleção: Desenvolver extratores de parâmetros

### ISSUE THREAD

**Issue by rafaelglater** [MPMG-DCC-UFMG/C04#5]
Criar um mecanismo para automaticamente extrair os parâmetros necessários (e seus possíveis valores) para a submissão dos formulários.

**Comment by rubia-rg** [comment]
- [ ] Extrair parâmetros necessários
- [ ] Detectar tipo de input para cada parâmetro
- [ ] Detectar parâmetros obrigatórios
