### ISSUE TITLE
Diário Oficial - prefeitura de Uberlândia

### ISSUE THREAD

**Issue by gabrielcrds** [MPMG-DCC-UFMG/C04#52]
https://www.uberlandia.mg.gov.br/prefeitura/orgaos-municipais/procuradoria-geral-do-municipio/diario-oficial-uberlandia/

**Comment by lucasaug** [comment]
Dados na host12, no arquivo /home/lucas/do-uberlandia.tar.gz

**Comment by lucasaug** [comment]
Dados movidos para o arquivo /mnt/lucas/52-do-uberlandia.tar.gz
