### ISSUE TITLE
Diário Oficial - prefeitura de Poços de Caldas

### ISSUE THREAD

**Issue by gabrielcrds** [MPMG-DCC-UFMG/C04#78]
https://pocosdecaldas.mg.gov.br/transparencia/diario-oficial-do-municipio/

**Comment by lucasaug** [comment]
Dados na host12, no arquivo /home/lucas/do-pocos-de-caldas.tar.gz

**Comment by lucasaug** [comment]
Dados movidos para o arquivo /mnt/lucas/78-do-pocos-de-caldas.tar.gz
