### ISSUE TITLE
Dados de Licitação fechadas - prefeitura de Muriae

### ISSUE THREAD

**Issue by gabrielcrds** [MPMG-DCC-UFMG/C04#79]
https://muriae.mg.gov.br/licitacao/

**Comment by lucasaug** [comment]
Dados na host12, no arquivo /home/lucas/licitacoes-muriae.tar.gz

**Comment by lucasaug** [comment]
Dados movidos para o arquivo /mnt/lucas/79-licitacoes-muriae.tar.gz
