### ISSUE TITLE
Diário Oficial - prefeitura de Itabirito

### ISSUE THREAD

**Issue by gabrielcrds** [MPMG-DCC-UFMG/C04#88]
http://www.itabirito.mg.gov.br/oficio/

**Comment by caiocvsilva** [comment]
Os dados se encontram no latin:

caio/diario-oficial-itabirito/

**Comment by gabrielcrds** [comment]
Movi os dados para a pasta _/mnt/caio_ . Favor salvar dentro de _/mnt_

**Comment by caiocvsilva** [comment]
Estrutura dos diretórios salvos:

No primeiro nível existe uma pasta com a data em que foi rodado o crawler. Dentro desta, no segundo nível, existe uma pasta por entrada, numeradas sequencialmente (1 até o número de entradas). Dentro de cada pasta numerada, nível três, se encontram os arquivos html daquela entrada.
